name: Deploy CV with gh-pages


on:
  workflow_dispatch:

  push:
    branches:
      - "master"
      - "main"


permissions:
  contents: write     


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Step
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          architecture: 'x64'
          check-latest: false
          registry-url: 'https://registry.npmjs.org/'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.7.5
          run_install: false

      - name: Install dependecies
        run:  pnpm install 
      
      - name: Build project
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # Branch on which I will deploy
          folder: build
